version: '3'

services:
  app:
    build: .
    image: jachinai/chatgpt-server
    container_name: chatgpt-server
    restart: always
    ports:
        - "3000:3000"
    volumes:
      - .env:/usr/src/.env
