version: '3'

services:
  chatgpt-server:
    image: jachinai/chatgpt-server:latest
    container_name: chatgpt-server
    restart: always
    ports:
        - "3000:3000"
    volumes:
      - .env:/usr/src/.env
